name: TensorFlow CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Steps:[1] Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} 
      
      - name: Steps:[2] Install dependent
        run: |
          # npm install 
          # npm run build
          export 
        env: 
          CI: true
          HAHA: hello_world

      - name: Steps:[3] Deploy Project
        run: |
          chmod 755 scripts/deploy.sh && ./scripts/deploy.sh
          # ./scripts/deploy.sh
          # bash ./scripts/deploy.sh
          ll -a
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_ACCESS_TOKEN_TENSORFLOW_CI }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./scripts/
          # PUBLISH_DIR: ./docs/.vuepress/dist

